### ISSUE TITLE
retag panics if it hits a broken symlink

### ISSUE THREAD

**Issue by jugglerchris** [maurizi/retag.rs#23]
Reproducing:

```
/tmp/test$ ln -s asdf jkl
/tmp/test$ retag
thread '<main>' panicked at 'Could not start file watcher', ../src/libcore/option.rs:334
/tmp/test$ rm jkl
/tmp/test$ retag
Running "ctags" "-f" "/tmp/retag.tvW630xsNh12/tags.temp" "--recurse" "/tmp/test"
```

I think this may be an issue in `notify.rs`; updating Cargo.toml to get v2.5.2 didn't fix the problem.

**Comment by maurizi** [comment]
Great catch! I think you're right that the bug may ultimately lie with `notify.rs`, I'll do some investigation and find out.

Thanks for reporting the issue!

**Comment by maurizi** [comment]
@jugglerchris I've run into a bit of confusion trying to track this down, which is probably not helped by it being possible for that panic to arise in a number of different ways.

I tried on Linux and I can't reproduce this, with either the version of `rsnotify` this project is pinned to or with the latest version of `rsnotify`.
What OS are you testing this on?  Do you have anything in `~/.config/retag.toml`?

**Comment by jugglerchris** [comment]
I'm on Linux too. I'll go back and recheck in the next few days when I'm sitting at a computer with a keyboard; maybe I was accidentally testing an old version of something, or some other similar mistake.  Apologies if so!
And thanks for looking into it either way!

**Comment by jugglerchris** [comment]
Ok, so I definitely still get a panic with a broken symlink.  I was previously on a not-that-recent CentOS machine, but just tried on my up to date Ubuntu machine, and I get the same panic if I run it in a directory after creating a broken symlink.
I'm not sure it adds much, but I ran it with RUST_BACKTRACE=1 and got this:

$ RUST_BACKTRACE=1 ./target/debug/retag 
thread '<main>' panicked at 'Could not start file watcher', ../src/libcore/option.rs:334
stack backtrace:
   1:     0x556de177aa50 - sys::backtrace::tracing::imp::write::h1fe79f3711caca0eUnt
   2:     0x556de177d815 - panicking::log_panic::_<closure>::closure.39701
   3:     0x556de177d261 - panicking::log_panic::hffc6d029fed602571nx
   4:     0x556de1769f93 - sys_common::unwind::begin_unwind_inner::h7045c1c64d9ab8edYgs
   5:     0x556de176a608 - sys_common::unwind::begin_unwind_fmt::h40ee994bfe85f7a54fs
   6:     0x556de177a121 - rust_begin_unwind
   7:     0x556de17a800f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x556de15d01e4 - option::_<impl>::expect::expect::h10147081162652256657
                        at ../src/libcore/macros.rs:28
   9:     0x556de15c815b - watcher::_<impl>::watch_project::hed74df21a1e0af3eOba
                        at src/watcher.rs:56
  10:     0x556de16055b4 - main::h4c8bae0e196f783epxa
                        at src/main.rs:51
  11:     0x556de177cfa4 - sys_common::unwind::try::try_fn::h5008875067004982501
  12:     0x556de1779f88 - __rust_try
  13:     0x556de177cc3f - rt::lang_start::h58cfae38546804729kx
  14:     0x556de160b739 - main
  15:     0x7f5c3d320a3f - __libc_start_main
  16:     0x556de15c6b68 - _start
  17:                0x0 - <unknown>

**Comment by jugglerchris** [comment]
Hi,
I _think_ this is fixed when moving to notify 2.5.3, rather than the 2.4 as in Cargo.toml.  I think I don't yet understand how Cargo.lock works, and wasn't always running what I thought I'd built.
Chris

**Comment by maurizi** [comment]
@jugglerchris I updated `notify` to `2.5.3` and published a new version of `retag` to crates.io, can you let me know if it works?

**Comment by jugglerchris** [comment]
Thanks - I can confirm I'm no longer having problems with broken symlinks.
